future: true
permalink: /:title/
url: http://8652.github.io
name: Gao Chen
author: Gao Chen
qq: 626531215
email: gao4411@qq.com

duoshuo: Gao chen
beian: 
cnzz: 
weibo: 
github: 8652
about: "这里是 Gao Chen 的个人博客，创建于 2018 年。"

safe: true
paginate: 20
